CREATE TABLE IF NOT EXISTS "teams"(
    "id" VARCHAR NOT NULL,
    "name" VARCHAR NOT NULL,
);
ALTER TABLE "teams" ADD CONSTRAINT IF NOT EXISTS "pk" PRIMARY KEY("id");

CREATE TABLE IF NOT EXISTS "team_members"(
    "team_id" VARCHAR NOT NULL,
    "user_id" VARCHAR NOT NULL,
    "contributor" BOOLEAN NOT NULL
);
ALTER TABLE "team_members" ADD CONSTRAINT IF NOT EXISTS "pk" PRIMARY KEY("team_id", "user_id");

ALTER TABLE "team_members" ADD CONSTRAINT IF NOT EXISTS "team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
ALTER TABLE "team_members" ADD CONSTRAINT IF NOT EXISTS "user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE NOCHECK;
